### ISSUE TITLE
Unknown function error on startup

### ISSUE THREAD

**Issue by dkasak** [kana/vim-operator-replace#5]
I get the following error when vim starts up with vim-operator-replace enabled: `E117: Unknown function: operator#user#define`

**Comment by dmdque** [comment]
Just thought I should mention that I also skimmed through the docs and missed that line.

**Comment by guyzmo** [comment]
Well, same here, hopefully a google search led here, but catching the lack of `vim-operator-user` and echoing out a nice user message to say "please install dependency" would be nice!
